#!/usr/bin/env bash
# iac/pack-chunks.sh
# Split a podman-save .tar into 100 MB chunks + write manifest.json
# + SHA256SUMS + reassemble.sh, all into iac/dist/.
#
# Usage:
#   ./pack-chunks.sh --input iac/dist/s7-fedora-base-vTAG.tar --tag vTAG
#   ./pack-chunks.sh --help

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/manifest.yaml"
DIST="$SCRIPT_DIR/dist"
LOG="$DIST/pack-chunks.log"
mkdir -p "$DIST"

INPUT=""
TAG=""
SIG_IN=""
for ((i=1; i<=$#; i++)); do
  case "${!i}" in
    --help|-h)
      sed -n '2,10p' "$0" | sed 's|^# \?||'
      exit 0 ;;
    --input) j=$((i+1)); INPUT="${!j}" ;;
    --tag)   j=$((i+1)); TAG="${!j}" ;;
    --sig)   j=$((i+1)); SIG_IN="${!j}" ;;
  esac
done

timestamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
log() { printf '%s  %s\n' "$(timestamp)" "$*" | tee -a "$LOG"; }
fail() { log "FAIL: $*"; exit 1; }

[[ -n "$INPUT" ]] || fail "--input required"
[[ -n "$TAG"   ]] || fail "--tag required"
[[ -f "$INPUT" ]] || fail "input file $INPUT not found"

# Resolve INPUT (+ optional SIG_IN) to absolute so cd-ing into DIST doesn't break it
INPUT="$(readlink -f "$INPUT")"
if [[ -n "$SIG_IN" ]]; then
  [[ -f "$SIG_IN" ]] || fail "signature file $SIG_IN not found"
  SIG_IN="$(readlink -f "$SIG_IN")"
fi

CHUNK_SIZE=$(python3 -c "import yaml; print(yaml.safe_load(open('$MANIFEST'))['build']['chunk_size_bytes'])")
BASENAME="s7-fedora-base-${TAG}.tar"
TOTAL_SIZE=$(stat -c %s "$INPUT")

log "=== pack-chunks.sh start ==="
log "input:      $INPUT ($TOTAL_SIZE bytes)"
log "tag:        $TAG"
log "chunk size: $CHUNK_SIZE bytes"

# Clean any previous chunks for this tag
rm -f "$DIST/${BASENAME}."[0-9]*

# Split using coreutils split
log "[1/3] splitting into ${CHUNK_SIZE}-byte chunks"
cd "$DIST"
split --bytes="$CHUNK_SIZE" --numeric-suffixes=0 --suffix-length=2 "$INPUT" "${BASENAME}."

# Compute hashes
log "[2/3] computing SHA256 for each chunk + reassembled total"
> SHA256SUMS
chunks_json=""
chunk_count=0
for chunk in "${BASENAME}."[0-9][0-9]; do
  [[ -f "$chunk" ]] || continue
  size=$(stat -c %s "$chunk")
  hash=$(sha256sum "$chunk" | awk '{print $1}')
  printf '%s  %s\n' "$hash" "$chunk" >> SHA256SUMS
  chunks_json+=$(python3 -c "import json; print(json.dumps({'file': '$chunk', 'size': $size, 'sha256': '$hash'}))")
  chunks_json+=","
  chunk_count=$((chunk_count + 1))
done
chunks_json="${chunks_json%,}"
REASSEMBLED_HASH=$(sha256sum "$INPUT" | awk '{print $1}')
printf '%s  %s\n' "$REASSEMBLED_HASH" "$(basename "$INPUT")" >> SHA256SUMS

# If a signature was provided, copy it into dist/ and include it in SHA256SUMS
SIG_FILENAME=""
if [[ -n "$SIG_IN" ]]; then
  SIG_FILENAME="${BASENAME}.sig"
  # If SIG_IN is already at DIST/SIG_FILENAME, skip the cp (same file)
  if [[ "$SIG_IN" != "$DIST/$SIG_FILENAME" ]]; then
    cp "$SIG_IN" "$DIST/$SIG_FILENAME"
  fi
  sig_hash=$(sha256sum "$SIG_FILENAME" | awk '{print $1}')
  printf '%s  %s\n' "$sig_hash" "$SIG_FILENAME" >> SHA256SUMS
  log "  included signature: $SIG_FILENAME"
fi

# Write manifest.json
log "[3/3] writing manifest.json and reassemble.sh"
SIG_JSON=""
if [[ -n "$SIG_FILENAME" ]]; then
  SIG_JSON=",\"signature\": {\"file\": \"${SIG_FILENAME}\", \"scheme\": \"ssh-ed25519\", \"namespace\": \"file\", \"identifier\": \"s7-skyqubi\"}"
fi
cat > "${BASENAME%.tar}.json" <<JSONEOF
{
  "name": "s7-fedora-base",
  "version": "${TAG}",
  "fork_of": "$(python3 -c "import yaml; m=yaml.safe_load(open('$MANIFEST')); print(m['fork_of']['registry']+'/'+m['fork_of']['image']+':'+str(m['fork_of']['tag']))")",
  "built_at": "$(timestamp)",
  "chunk_count": ${chunk_count},
  "chunk_size_bytes": ${CHUNK_SIZE},
  "total_size_bytes": ${TOTAL_SIZE},
  "reassembled_sha256": "${REASSEMBLED_HASH}",
  "chunks": [${chunks_json}]${SIG_JSON}
}
JSONEOF

cat > reassemble.sh <<REASSEMEOF
#!/usr/bin/env bash
# Auto-generated by iac/pack-chunks.sh — reassemble, verify, and (if
# s7-image-signing.pub + .sig present) cryptographically verify
# before loading.
#
# Usage: run this script from the directory containing all
#        s7-fedora-base-${TAG}.tar.NN chunks + SHA256SUMS +
#        optionally the .sig file + s7-image-signing.pub.

set -euo pipefail
TAG="${TAG}"
BASENAME="s7-fedora-base-\${TAG}.tar"
SIG_FILE="\${BASENAME}.sig"
PUB_KEY="s7-image-signing.pub"

echo "=== Verifying chunks ==="
sha256sum -c SHA256SUMS --ignore-missing || { echo "FAIL: chunk verification"; exit 1; }

echo "=== Reassembling to \$BASENAME ==="
cat "\$BASENAME".[0-9][0-9] > "\$BASENAME"

echo "=== Verifying full tar hash ==="
sha256sum -c SHA256SUMS --ignore-missing --quiet || { echo "FAIL: reassembled verification"; exit 1; }

if [[ -f "\$SIG_FILE" && -f "\$PUB_KEY" ]]; then
  echo "=== Verifying ssh-ed25519 signature ==="
  # ssh-keygen -Y verify needs an allowed_signers file, not the raw pub key.
  # Build one on the fly: one line "<principal> <pubkey-content>".
  ALLOWED=\$(mktemp)
  trap "rm -f \$ALLOWED" EXIT
  printf 's7-skyqubi %s\n' "\$(cat "\$PUB_KEY")" > "\$ALLOWED"
  if ssh-keygen -Y verify -f "\$ALLOWED" -I s7-skyqubi -n file -s "\$SIG_FILE" < "\$BASENAME" 2>/dev/null; then
    echo "Good signature against \$PUB_KEY"
  else
    echo "FAIL: signature verification failed — image may be tampered"
    exit 1
  fi
elif [[ -f "\$SIG_FILE" && ! -f "\$PUB_KEY" ]]; then
  echo "WARNING: \$SIG_FILE present but \$PUB_KEY missing — cannot verify signature"
  echo "Download s7-image-signing.pub from the S7 sovereignty repo and retry."
  exit 1
else
  echo "NOTE: no signature file — proceeding without signature verification"
  echo "      (unsigned builds are for development only)"
fi

echo "=== Loading into podman ==="
podman load -i "\$BASENAME"

echo "=== Done ==="
podman images | grep s7-fedora-base
REASSEMEOF
chmod +x reassemble.sh

log "wrote:"
log "  ${chunk_count} chunks: ${BASENAME}.00 .. ${BASENAME}.$(printf '%02d' $((chunk_count-1)))"
log "  ${BASENAME%.tar}.json"
log "  SHA256SUMS"
log "  reassemble.sh"
log "=== pack-chunks.sh complete ==="
exit 0
